parameters:
  - name: tfModulePath
    type: string
    default: "."
  - name: tfVersion
    type: string
    default: "1.7.5"
  - name: azServiceConnection
    type: string
  - name: tfStateAzSaRG
    type: string
  - name: tfStateAzSa
    type: string
  - name: tfStateAzSaCont
    type: string
  - name: tfStateName
    type: string
    default: "terraform.tfstate"
  - name: envInstallList
    type: object


stages:
  - ${{each stage in parameters.envInstallList}}:
    - stage: ${{ replace(stage.env, '-', '_') }}_${{ replace(stage.workspace, '-', '_') }}_execute_terraform
      displayName: "${{ stage.env }} :: Execute terraform"
      condition: always()
      jobs:
        - template: jobs/execute.yml
          parameters:
            tfvars: "${{ stage.tfvars }}"
            tfModulePath: "${{ parameters.tfModulePath }}"
            tfVersion: "${{ parameters.tfVersion }}"
            azServiceConnection: "${{ parameters.azServiceConnection }}"
            tfStateAzSaRG: "${{ parameters.tfStateAzSaRG }}"
            tfStateAzSa: "${{ parameters.tfStateAzSa }}"
            tfStateAzSaCont: "${{ parameters.tfStateAzSaCont }}"
            tfStateName: "${{ parameters.tfStateName }}"
            tfworkspace: "${{ stage.env }}${{ stage.workspace }}"
