parameters:
  - name: tfModulePath
    type: string
  - name: tfVersion
    type: string
  - name: azServiceConnection
    type: string
  - name: tfStateAzSaRG
    type: string
  - name: tfStateAzSa
    type: string
  - name: tfStateAzSaCont
    type: string
  - name: tfStateName
    type: string
  - name: env
    type: string
  - name: app
    type: string

jobs:
  - job: Validate
    displayName: Format and Validate
    pool:
      name: ubuntu-docker
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: echo "1*** ${TF_WORKSPACE}"
        env:
          TF_WORKSPACE: "{{ parameters.env }}${{ parameters.app }}"
      - template: ../steps/tf-init.yml
        parameters:
          tfModulePath: "${{ parameters.tfModulePath }}"
          tfVersion: "${{ parameters.tfVersion }}"
          azServiceConnection: "${{ parameters.azServiceConnection }}"
          tfStateAzSaRG: "${{ parameters.tfStateAzSaRG }}"
          tfStateAzSa: "${{ parameters.tfStateAzSa }}"
          tfStateAzSaCont: "${{ parameters.tfStateAzSaCont }}"
          tfStateName: "${{ parameters.tfStateName }}"
          env: "${{ parameters.env }}"
          app: "${{ parameters.app }}"

      - template: ../steps/tf-validate.yml
        parameters:
          azServiceConnection: "${{ parameters.azServiceConnection }}"
