parameters:
  - name: azServiceConnection
    type: string

jobs:
  - job: Validate
    displayName: Format and Validate
    pool:
      name: ubuntu-docker
    steps:
      - template: ../steps/tf-validate.yml
        parameters:
          azServiceConnection: "${{ parameters.azServiceConnection }}"
